# Site settings
name: Hongqiao (Henry) Li
email: lhq.day@gmail.com

keywords: "Software Engineer, Natural Language Processing, Computer Vision, Machine Learning, Deep Learning, Artificial Intelligence, C++, Python"
skills: "Software Engineer in Natural Language Processings"
baseurl:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# You should replace these with your social networks, of course. :)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/hongqiaoli/
  - title: github
    url: https://github.com/henrylih
#  - title: medium
#    url: https://medium.com/@xpharry
    
# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 2196F3
  primary-rgb: "33, 180, 243"
  secondary: 285172
  secondary-dark: 29455b
  section-tout: eaf1f1

address:
  - line: Mountain View, CA 94043
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
